version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

root:
  level: WARN
  handlers: [console]

loggers:
  server.app:
    level: DEBUG
    handlers: [console]
    propagate: no

  server.orchestrator:
    level: DEBUG
    handlers: [console]
    propagate: no

  server.interfaces:
      level: DEBUG
      handlers: [console]
      propagate: no

  server.managers:
      level: DEBUG
      handlers: [console]
      propagate: no

  server.rest_api:
      level: DEBUG
      handlers: [console]
      propagate: no

  server.rest_api:
      level: DEBUG # Must be set to INFO to be active
      handlers: [console]
      propagate: no
