SYSTEM:
    livebox_fw version: echo LIVEBOX VERSION NOT IMPLEMENTED
WIFI:
    status:
        - wl -i wl2 bss
        - wl -i wl0 bss
        - wl -i wl1 bss
    ON:
        - wl -i wl0 radio on
        - wl -i wl2 radio on
        - wl -i wl1 radio on
    OFF:
        - wl -i wl0 radio off
        - wl -i wl2 radio off
        - wl -i wl1 radio off
    bands:
        2.4GHz:
            status: wl -i wl2 bss
            ON: wl -i wl2 radio on
            OFF: wl -i wl2 radio off
            stations: wl -i wl2 assoclist
        5GHz:
            status: wl -i wl0 bss
            ON: wl -i wl0 radio on
            OFF: wl -i wl0 radio off
            stations: wl -i wl0 assoclist
        6GHz:
            status: wl -i wl1 bss
            ON: wl -i wl1 radio on
            OFF: wl -i wl1 radio off
            stations: wl -i wl1 assoclist
