version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

  app:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/app.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  orchestrator:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/orchestrator/orchestrator.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  orchestrator_notification:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/orchestrator/orchestrator_notification.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  orchestrator_live_objects:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/orchestrator/orchestrator_live_objects.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  orchestrator_polling:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/orchestrator/orchestrator_polling.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  orchestrator_requests:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/orchestrator/orchestrator_requests.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  orchestrator_use_situations:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/orchestrator/orchestrator_use_situations.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  api_rest:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/api-rest.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_mqtt:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/mqtt.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_camera:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/camera.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_electrical_panel:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/electrical_panel.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_thread:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/thread.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_wifi_bands:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/wifi_bands.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_alimelo:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/alimelo.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  interface_mqtt:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/interface/mqtt.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  interface_live_objects:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/interface/live_objects.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  interface_thread:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/interface/thread.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  interface_telnet:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/interface/telnet.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  interface_alimelo:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/interface/alimelo.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

root:
  level: WARN
  handlers: [app]

loggers:
  server.app:
    level: INFO
    handlers: [console]
    propagate: no

  server.rest_api:
      level: INFO
      handlers: [api_rest]
      propagate: no

  server.orchestrator.service:
    level: INFO
    handlers: [orchestrator]
    propagate: no

  server.orchestrator.notification:
    level: INFO
    handlers: [orchestrator_notification]
    propagate: no

  server.orchestrator.live_objects:
    level: INFO
    handlers: [orchestrator_live_objects]
    propagate: no

  server.orchestrator.polling:
    level: INFO
    handlers: [orchestrator_polling]
    propagate: no

  server.orchestrator.requests:
    level: INFO
    handlers: [console]
    propagate: no

  server.orchestrator.use_situations:
    level: INFO
    handlers: [orchestrator_use_situations]
    propagate: no

  server.managers.mqtt_manager:
    level: INFO
    handlers: [manager_mqtt]
    propagate: no

  server.managers.camera_manager:
    level: INFO
    handlers: [manager_camera]
    propagate: no

  server.managers.electrical_panel_manager:
    level: INFO
    handlers: [manager_electrical_panel]
    propagate: no

  server.managers.thread_manager:
    level: INFO
    handlers: [manager_thread]
    propagate: no

  server.managers.wifi_bands_manager:
    level: INFO
    handlers: [manager_wifi_bands]
    propagate: no

  server.managers.alimelo_manager:
    level: DEBUG
    handlers: [manager_alimelo]
    propagate: no

  server.interfaces.thread_interface:
    level: DEBUG
    handlers: [interface_thread]
    propagate: no

  server.interfaces.mqtt_interface:
    level: INFO
    handlers: [interface_mqtt]
    propagate: no

  server.interfaces.live_objects_interface:
    level: INFO
    handlers: [interface_live_objects]
    propagate: no

  server.interfaces.wifi_interface:
    level: INFO
    handlers: [interface_telnet]
    propagate: no

  server.interfaces.alimelo_interface:
    level: DEBUG
    handlers: [interface_alimelo]
    propagate: no

