API_TITLE: ORCHESTRATOR API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# Telnet connection configuration
LIVEBOX_IP_ADDRESS: 192.168.1.1 # LIVEBOX
LIVEBOX_TELNET_PORT: 23
LIVEBOX_LOGIN: root
LIVEBOX_PASSWORD: sah
TELNET_TIMOUT_IN_SECS: 5
LIVEBOX_TELNET_COMMANDS: server_box/server/config/telnet_commands.yml

# Use situations configuration
USE_SITUATIONS_CONFIG: server_box/server/config/use_situations.yml
DEFAULT_USE_SITUATION: PRESENCE_HOME_OFFICE

# Thread configuration
THREAD_SERIAL_INTERFACE: /dev/ttyAMA0
THREAD_SERIAL_SPEED: 115200

# MQTT CONFIGURATION
#MQTT_BROKER_ADDRESS: 192.168.1.33 #Electrical pannel
#MQTT_BROKER_ADDRESS: 192.168.1.16 #RPI cloud
MQTT_BROKER_ADDRESS: 192.168.1.19 #VM
MQTT_USERNAME: rpi_box
MQTT_PASSWORD: lamp
MQTT_QOS: 1
MQTT_RECONNECTION_TIMEOUT_IN_SEG: 1
MQTT_MAX_RECONNECTION_ATTEMPS: 3
MQTT_MSG_PUBLISH_TIMEOUT_IN_SECS: 5
MQTT_ALARM_NOTIFICATION_TOPIC: alarm/notification
MQTT_COMMAND_TOPIC: command/general

# ELECTRICAL PANEL CONFIGURATION
MQTT_COMMAND_RELAYS_TOPIC: command/relays
MQTT_RELAYS_STATUS_TOPIC: status/relays

# RESOURCES STATUS POLLING CONFIGURATION
WIFI_STATUS_POLLING_PERIOD_IN_SECS: 8
ALIMELO_STATUS_CHECK_PERIOD_IN_SECS: 45
THREAD_NODES_CHECK_PERIOD_IN_SECS: 10

# WIFI NOTIFICATION CONFIGURATION
MQTT_WIFI_STATUS_RELAYS_TOPIC: wifi/status/relays

# RPI CLOUD SERVER CONFIGURATION
#RPI_CLOUD_IP: cloudwigreen.ddns.net
#RPI_CLOUD_IP: 192.168.1.16  #RPI CLOUD CONNECTED IN LOCAL BOX
RPI_CLOUD_IP: 192.168.1.19  #VM
#RPI_CLOUD_IP: localhost #VM local
RPI_CLOUD_PORTS:
  - 3000
#  - 3001
RPI_CLOUD_NOTIFY_STATUS_PATH: status
RPI_CLOUD_NOTIFY_ALARM_PATH: alarm
RPI_CLOUD_DEVICE_PATH: objects
RPI_CLOUD_THREAD_NODES_PATH: thread_nodes

# ALIMELO COMMUNICATION CONFIG
ALIMELO_SERIAL_PORT: /dev/ttyACM0
ALIMELO_NOTIFICATION_SEPARATOR: ORCHESTRATOR_SERIAL_NOTIFICATION
ALIMELO_COMMAND_SEPARATOR: ORCHESTRATOR_SERIAL_COMMAND
ALIMELO_SERIAL_CONNECTION_RESTART_TIMEOUT_IN_SECS: 30

# LIVE OBJECTS CONFIG
LIVE_OBJECTS_NOTIFICATION_PERIOD_IN_SECS: 60

# HOME OFFICE USE SITUATION TRIGGER MAC ADDRESS
HOME_OFFICE_MAC_ADDR: 96:35:5C:89:D3:5A

ORCHESTRATOR_COMMANDS: server_box/server/config/orchestrator_commands.yml
