THREAD:
    NETWORK_SETUP_COMMANDS:
      - "ot-ctl udp close"
      - "ot-ctl ifconfig down"
      - "ot-ctl dataset init new"
      - "ot-ctl dataset commit active"
      - "ot-ctl ifconfig up"
      - "ot-ctl thread start"
      - "ot-ctl ipaddr"
      - "ot-ctl dataset active -x"
      - "ot-ctl udp open"
      - "ot-ctl udp bind :: 45"

    NODES:
      - name: rpi_camera
        id: cam
