USE_SITUATIONS:
  PRESENCE_HOME_OFFICE:
    SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    100%:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: True
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: True
      POWER_STRIP:
        1: True
        2: True
        3: True
        4: True
    25%:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: True
      ELECTRICAL_OUTLETS:
        0: False
        1: True
        2: True
      POWER_STRIP:
        1: True
        2: True
        3: False
        4: False
    0%:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: True
      POWER_STRIP:
        1: True
        2: False
        3: False
        4: False
  PRESENCE_DAY_LOW_CONSUMPTION:
    SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    100%:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: True
      POWER_STRIP:
        1: True
        2: True
        3: False
        4: False
    25%:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: True
        2: True
      POWER_STRIP:
        1: True
        2: False
        3: False
        4: False
    0%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: True
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
  PRESENCE_NIGHT_LOW_CONSUMPTION:
    SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    100%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: True
      POWER_STRIP:
        1: True
        2: False
        3: False
        4: False
    25%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: True
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
    0%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: True
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
  ABSENCE_LOW_CONSUMPTION:
    SWITCH_TO: PRESENCE_DAY_LOW_CONSUMPTION
    100%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
    25%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
    0%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
  DEEP_SLEEP:
    SWITCH_TO: PRESENCE_DAY_LOW_CONSUMPTION
    100%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
    25%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
    0%:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      POWER_STRIP:
        1: False
        2: False
        3: False
        4: False
