USE_SITUATIONS:
    PRESENCE_HOME_OFFICE:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: True
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: True
      SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    PRESENCE_DAY_HIGH_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: True
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: True
      SWITCH_TO: ABSENCE_HIGH_CONSUMPTION
    PRESENCE_DAY_LOW_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: False
      SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    PRESENCE_NIGHT_HIGH_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: False
      SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    PRESENCE_NIGHT_LOW_CONSUMPTION:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: True
      SWITCH_TO: ABSENCE_LOW_CONSUMPTION
    ABSENCE_HIGH_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: True
        1: False
        2: False
      SWITCH_TO: PRESENCE_DAY_LOW_CONSUMPTION
    ABSENCE_LOW_CONSUMPTION:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: False
        1: False
        2: False
      SWITCH_TO: PRESENCE_DAY_LOW_CONSUMPTION
    ABSENCE_HIGH_CONSUMPTION_REMOTE_ACCESS:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: False
      ELECTRICAL_OUTLETS:
        0: True
        1: True
        2: False
      SWITCH_TO: PRESENCE_DAY_LOW_CONSUMPTION
