USE_SITUATIONS:
    PRECENCE_HOME_OFFICE:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: True
      ELECTRICAL_OUTLETS:
        1: True
        2: True
        3: True
    PRECENCE_DAY_HIGH_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: True
      ELECTRICAL_OUTLETS:
        1: True
        2: True
        3: True
    PRECENCE_DAY_LOW_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: False
      ELECTRICAL_OUTLETS:
        1: True
        2: True
        3: False
    PRECENCE_NIGHT_HIGH_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        1: True
        2: False
        3: False
    PRECENCE_NIGHT_LOW_CONSUMPTION:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        1: False
        2: False
        3: False
    ABSENCE_HIGH_CONSUMPTION:
      WIFI:
        2.4GHz: True
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        1: True
        2: False
        3: False
    ABSENCE_LOW_CONSUMPTION:
      WIFI:
        2.4GHz: False
        5GHz: False
        6GHz: False
      ELECTRICAL_OUTLETS:
        1: False
        2: False
        3: False
    ABSENCE_HIGH_CONSUMPTION_REMOTE_ACCESS:
      WIFI:
        2.4GHz: True
        5GHz: True
        6GHz: False
      ELECTRICAL_OUTLETS:
        1: True
        2: True
        3: False
